<?php

return [
    'paginate' => 15,
    'article' => 'Tin tức',
    'product' => 'Sản phẩm',
    'active' => 'hoạt động',
    'inactive' => 'Không hoạt động',
    'Retailers' => 'Nhà phân phối',
    'Distributors' => 'Cửa hàng đại lý',
    'Installers' => 'Thầu thợ',
    'classic' => 'Cổ điển', 
    'modern' => 'Hiện đại', 
    'brochure/Leaflet' => 'Brochure/Leaflet',
    'certificates' => 'Giấy chứng nhận',
    'drawings' => 'Bản vẽ',
    'installation Guide' => 'Hướng dẫn thi công',
    'submittal Sheet' => 'Submittal Sheet',
    'test reports' => 'Kết quả thử nghiệm',
    'vi' => [
        'product_name' => 'Tên sản phẩm',
        'category_name' => 'Tên danh mục',
        'address' => 'Địa chỉ',
        'construction_area' => 'Khu vực thi công',
        'description' => 'Mô tả',
        'content' => 'Nội dung',
        'title' => 'Tiêu đề',
        'location' => 'Vị trí',
        'city' => 'Thành phố',
        'region' => 'Khu vực thi công',
        'name' => 'Tên',
        'question' => 'Câu hỏi',
        'answer' => 'Câu trả lời',
        'unit' => 'Đơn vị đo'
    ],

    'en' => [
        'product_name' => 'Tên sản phẩm',
        'category_name' => 'Tên danh mục',
        'address' => 'Địa chỉ',
        'construction_area' => 'Khu vực thi công',
        'description' => 'Mô tả',
        'content' => 'Nội dung',
        'title' => 'Tiêu đề',
        'location' => 'Vị trí',
        'city' => 'Thành phố',
        'region' => 'Khu vực thi công',
        'name' => 'Tên',
        'question' => 'Câu hỏi',
        'answer' => 'Câu trả lời',
        'unit' => 'Đơn vị đo'
    ],

    'material_types' => [
        'tcxcpt' => 'Tran chim xuong ca pho thong',
        'tcxccc' => 'Tran chim xuong ca cao cap',
        'tcddpt' => 'Tran chim dong dang pho thong',
        'tcddcc' => 'Tran chim đong dang cao cap',
        'tnpt' => 'Tran noi pho thong',
        'vc' => 'Vach chay',
        'vcc1' => 'Vach chong chay 1 gio',
        'vcc2' => 'Vach chong chay 2 gio',
    ],
];    
